name: Build macOS binaries
on: [push, pull_request]

jobs:
  build_macos:
    name: Build macOS binary
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Build (x64)
        run: |
          cd ${GITHUB_WORKSPACE}/CPP/7zip/Bundles/Alone2
          make -j -f ../../cmpl_mac_x64.mak
          ls -ltr
      - name: Build (arm64)
        run: |
          cd ${GITHUB_WORKSPACE}/CPP/7zip/Bundles/Alone2
          make -j -f ../../cmpl_mac_arm64.mak
      - name: Test
        run: |
          ${GITHUB_WORKSPACE}/CPP/7zip/Bundles/Alone2/b/7zz b
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: "**/7zz"
          name: macOS Binaries
