name: Build Linux / etc binaries
on: [push, pull_request]

jobs:
  cargo_tests:
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          { "os": "ubuntu-latest",  "name": "Linux" },
          { "os": "macOS-latest",   "name": "macOS" },
          { "os": "windows-latest", "name": "Windows" },
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Build (x64)
        run: |
          cd ${GITHUB_WORKSPACE}/CPP/7zip/Bundles/Alone2
          ls -ltr
